"""New Interview attribute

Revision ID: 0e493cd3b9b6
Revises: 105c8bce3cad
Create Date: 2024-06-25 16:06:19.765678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e493cd3b9b6'
down_revision = '105c8bce3cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
