"""New Interview attribute

Revision ID: 105c8bce3cad
Revises: 38a30ba2392f
Create Date: 2024-06-25 16:01:22.526443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105c8bce3cad'
down_revision = '38a30ba2392f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
