"""New Admin class for admin role creation

Revision ID: 24601ac21595
Revises: 41e8f9ddf473
Create Date: 2024-06-28 16:10:51.455522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24601ac21595'
down_revision = '41e8f9ddf473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
