"""New 'InterviewParamter' model with only non required attributes (need to change) to not crash the application

Revision ID: 38a30ba2392f
Revises: 9f6802458661
Create Date: 2024-06-24 15:20:15.083679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a30ba2392f'
down_revision = '9f6802458661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('role_description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('evaluation_criteria', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('interview_url', sa.String(), nullable=True))
        batch_op.drop_column('topic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('interview_url')
        batch_op.drop_column('evaluation_criteria')
        batch_op.drop_column('industry')
        batch_op.drop_column('role_description')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
