"""New migration

Revision ID: 443c46e11f88
Revises: 8485a500627c
Create Date: 2024-07-18 17:54:14.494791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443c46e11f88'
down_revision = '8485a500627c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.alter_column('max_questions',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.alter_column('max_questions',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
