"""new model to include a form that needs to be filled by the applicant in order to see his feedback

Revision ID: 545850b3bf80
Revises: 0e493cd3b9b6
Create Date: 2024-06-25 17:36:48.450079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545850b3bf80'
down_revision = '0e493cd3b9b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_rating')
    op.drop_table('review')
    # ### end Alembic commands ###
