"""New ponderation added for interview_parameter

Revision ID: 5478bda384a9
Revises: 9116fd8a2bf2
Create Date: 2024-08-06 11:08:33.937955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5478bda384a9'
down_revision = '9116fd8a2bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ponderation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.drop_column('ponderation')

    # ### end Alembic commands ###
