"""New attribute for Session class: thread_id and assistant_id

Revision ID: 55762b810275
Revises: 6d2fd719abfc
Create Date: 2024-07-09 19:16:01.495399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55762b810275'
down_revision = '6d2fd719abfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('assistant_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('assistant_id')
        batch_op.drop_column('thread_id')

    # ### end Alembic commands ###
