"""New attribute for Session: finished, default  = False

Revision ID: 72f0cc5eea66
Revises: d0478d77e065
Create Date: 2024-07-04 18:15:31.492198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72f0cc5eea66'
down_revision = 'd0478d77e065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('finished')

    # ### end Alembic commands ###
