"""Initial migration.

Revision ID: 853c257accf9
Revises: 2339e2e660cb
Create Date: 2024-06-17 14:29:54.420142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853c257accf9'
down_revision = '2339e2e660cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_names', sa.String(), nullable=False))
        batch_op.drop_column('contact_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('contact_names')

    # ### end Alembic commands ###
