"""Initial migration.

Revision ID: 9f6802458661
Revises: 853c257accf9
Create Date: 2024-06-17 14:30:08.092740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6802458661'
down_revision = '853c257accf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_name', sa.String(), nullable=False))
        batch_op.drop_column('contact_names')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_names', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('contact_name')

    # ### end Alembic commands ###
