"""New migration: updated HR model for authentication

Revision ID: bb771cec775a
Revises: adc1e10311dc
Create Date: 2024-06-27 15:50:37.978148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb771cec775a'
down_revision = 'adc1e10311dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('email_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_address', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('admin')
        batch_op.drop_column('confirmed')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
