"""new interview parameter model for situations

Revision ID: bef76ca30899
Revises: 9d013a2f99f1
Create Date: 2024-07-15 20:12:09.853823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef76ca30899'
down_revision = '9d013a2f99f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.alter_column('situation',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.alter_column('situation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
