"""New attribute for interview parameter: subrole and title

Revision ID: c5bff5c3b152
Revises: 443c46e11f88
Create Date: 2024-08-01 08:38:00.431995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bff5c3b152'
down_revision = '443c46e11f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('subrole', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_parameter', schema=None) as batch_op:
        batch_op.drop_column('subrole')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
